#!/usr/bin/env python3
"""Publish heatmap-guided fake occupied-cell claims for ROS 2 experiments.

This node does not spawn physical Gazebo obstacles. It reads the offline attack
heatmap generated by ``generate_attack_heatmap.py`` and publishes malicious
occupancy claims on ``/map_claims`` using the JSON schema already accepted by
``experiment_manager_node.py``.

The node supports three placement policies:

- ``topology_only``: choose the highest-scoring eligible heatmap cell.
- ``route_informed``: prefer high-scoring cells on or near the primary robot's
  currently published route.
- ``route_only``: only choose cells that lie on the primary robot's route.

All runtime behavior is contained in this file. Configuration is exposed as ROS
parameters so the launch file can pass the same map, goal count, and seeds used
by the experiment manager and heatmap generator.
"""

from __future__ import annotations

import json
import math
import os
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import rclpy
import yaml
from ament_index_python.packages import get_package_share_directory
from nav_msgs.msg import Path as NavPath
from rclpy.node import Node
from std_msgs.msg import String


Cell = Tuple[int, int]  # (row, column)


@dataclass(frozen=True)
class HeatmapCell:
    row: int
    col: int
    score: float
    route_frequency: float
    detour_impact: float
    chokepoint: float

    @property
    def cell(self) -> Cell:
        return self.row, self.col


class MaliciousObjectNode(Node):
    """Select heatmap cells and publish fake occupied claims."""

    def __init__(self) -> None:
        super().__init__("malicious_object_node")

        # Parameters shared with the experiment launch.
        self.declare_parameter("map_name", "room-32-32-4")
        self.declare_parameter("scenario_file", "scenario.yaml")
        self.declare_parameter("action_goal_count", -1)
        self.declare_parameter("action_goal_seed", -1)
        self.declare_parameter("reconnaissance_seed", -1)
        self.declare_parameter("heatmap_path", "")
        self.declare_parameter(
            "heatmap_directory",
            "~/.ros/trust_costmap/attack_heatmaps",
        )

        # Attack identity and timing.
        self.declare_parameter("enabled", True)
        self.declare_parameter("attacker_id", "")
        self.declare_parameter("primary_robot_id", "")
        self.declare_parameter("start_delay_sec", 20.0)
        self.declare_parameter("report_period_sec", 5.0)
        self.declare_parameter("max_attack_events", 0)

        # Claim and fake-object shape.
        self.declare_parameter("confidence", 0.95)
        self.declare_parameter("report_trust", -1.0)
        self.declare_parameter("fake_object_radius_cells", 0)
        self.declare_parameter("max_claims_per_event", 1)

        # Placement controls.
        self.declare_parameter("placement_policy", "topology_only")
        self.declare_parameter("selection_mode", "highest")
        self.declare_parameter("selection_seed", 21)
        self.declare_parameter("random_top_k", 5)
        self.declare_parameter("minimum_heatmap_score", 0.0)
        self.declare_parameter("route_relevance_weight", 1.0)
        self.declare_parameter("route_distance_scale_cells", 3.0)
        self.declare_parameter("report_range_cells", 0.0)
        self.declare_parameter("ego_exclusion_radius_cells", 2.0)
        self.declare_parameter("endpoint_exclusion_radius_cells", 1.0)
        self.declare_parameter("cell_cooldown_sec", 15.0)
        self.declare_parameter("allow_repeat_object_center", False)

        # Topics.
        self.declare_parameter("claim_topic", "/map_claims")
        self.declare_parameter("plan_status_topic", "/plan_status")

        self.package_share = get_package_share_directory("trust_costmap")
        self.map_name = str(self.get_parameter("map_name").value)
        self.scenario_file = str(self.get_parameter("scenario_file").value)
        self.scenario = self.load_scenario()

        self.cell_size_m = float(
            self.scenario.get("visualization", {}).get("cell_size_m", 0.5)
        )
        if self.cell_size_m <= 0.0:
            raise ValueError("visualization.cell_size_m must be positive")

        self.enabled = bool(self.get_parameter("enabled").value)
        self.attacker_id = self.resolve_attacker_id()
        self.primary_robot_id = self.resolve_primary_robot_id()

        self.start_delay_sec = max(
            0.0, float(self.get_parameter("start_delay_sec").value)
        )
        self.report_period_sec = max(
            0.05, float(self.get_parameter("report_period_sec").value)
        )
        self.max_attack_events = max(
            0, int(self.get_parameter("max_attack_events").value)
        )
        self.confidence = self.clamp01(
            float(self.get_parameter("confidence").value)
        )
        self.report_trust = float(self.get_parameter("report_trust").value)
        self.fake_object_radius_cells = max(
            0, int(self.get_parameter("fake_object_radius_cells").value)
        )
        self.max_claims_per_event = max(
            1, int(self.get_parameter("max_claims_per_event").value)
        )

        self.placement_policy = str(
            self.get_parameter("placement_policy").value
        ).strip().lower()
        if self.placement_policy not in {
            "topology_only",
            "route_informed",
            "route_only",
        }:
            raise ValueError(
                "placement_policy must be topology_only, route_informed, "
                "or route_only"
            )

        self.selection_mode = str(
            self.get_parameter("selection_mode").value
        ).strip().lower()
        if self.selection_mode not in {"highest", "random_top_k"}:
            raise ValueError("selection_mode must be highest or random_top_k")

        self.random_top_k = max(1, int(self.get_parameter("random_top_k").value))
        self.minimum_heatmap_score = max(
            0.0, float(self.get_parameter("minimum_heatmap_score").value)
        )
        self.route_relevance_weight = max(
            0.0, float(self.get_parameter("route_relevance_weight").value)
        )
        self.route_distance_scale_cells = max(
            1e-6,
            float(self.get_parameter("route_distance_scale_cells").value),
        )
        self.report_range_cells = max(
            0.0, float(self.get_parameter("report_range_cells").value)
        )
        self.ego_exclusion_radius_cells = max(
            0.0,
            float(self.get_parameter("ego_exclusion_radius_cells").value),
        )
        self.endpoint_exclusion_radius_cells = max(
            0.0,
            float(self.get_parameter("endpoint_exclusion_radius_cells").value),
        )
        self.cell_cooldown_sec = max(
            0.0, float(self.get_parameter("cell_cooldown_sec").value)
        )
        self.allow_repeat_object_center = bool(
            self.get_parameter("allow_repeat_object_center").value
        )

        selection_seed = int(self.get_parameter("selection_seed").value)
        self.rng = random.Random(selection_seed)

        self.heatmap_path = self.resolve_heatmap_path()
        self.heatmap_payload, self.heatmap_cells = self.load_heatmap(
            self.heatmap_path
        )
        self.heatmap_by_cell: Dict[Cell, HeatmapCell] = {
            item.cell: item for item in self.heatmap_cells
        }
        self.validate_heatmap_identity()

        self.primary_route: List[Cell] = []
        self.attacker_route: List[Cell] = []
        self.plan_status: Dict = {}
        self.last_attack_time_by_cell: Dict[Cell, float] = {}
        self.used_object_centers: Set[Cell] = set()
        self.attack_event_count = 0
        self.start_time_sec = self.now_sec()

        claim_topic = str(self.get_parameter("claim_topic").value)
        plan_status_topic = str(self.get_parameter("plan_status_topic").value)

        self.claim_pub = self.create_publisher(String, claim_topic, 50)
        self.plan_status_sub = self.create_subscription(
            String,
            plan_status_topic,
            self.plan_status_callback,
            20,
        )
        self.primary_route_sub = self.create_subscription(
            NavPath,
            f"/agent_routes/{self.primary_robot_id}",
            self.primary_route_callback,
            20,
        )
        self.attacker_route_sub = self.create_subscription(
            NavPath,
            f"/agent_routes/{self.attacker_id}",
            self.attacker_route_callback,
            20,
        )

        self.attack_timer = self.create_timer(
            self.report_period_sec,
            self.attack_timer_callback,
        )

        self.print_startup_summary()

    # ------------------------------------------------------------------
    # Loading and validation
    # ------------------------------------------------------------------

    def load_scenario(self) -> Dict:
        scenario_path = Path(self.package_share) / self.scenario_file
        if not scenario_path.exists():
            raise FileNotFoundError(f"Scenario file not found: {scenario_path}")
        data = yaml.safe_load(scenario_path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError(
                f"Scenario must contain a YAML mapping: {scenario_path}"
            )
        return data

    def resolve_attacker_id(self) -> str:
        requested = str(self.get_parameter("attacker_id").value).strip()
        if requested:
            return requested

        for robot in self.scenario.get("robots", []):
            if not robot.get("enabled", True):
                continue
            role = str(robot.get("role", "")).strip().lower()
            if "malicious" in role:
                return str(robot["id"])

        raise ValueError(
            "No enabled malicious robot was found in scenario.yaml and "
            "attacker_id was not provided"
        )

    def resolve_primary_robot_id(self) -> str:
        requested = str(self.get_parameter("primary_robot_id").value).strip()
        if requested:
            return requested

        evaluation_id = str(
            self.scenario.get("evaluation", {}).get("primary_robot", "")
        ).strip()
        if evaluation_id:
            return evaluation_id

        preferred_roles = {
            "navigation_robot",
            "navigator",
            "ego",
            "ego_robot",
            "benign_navigator",
        }
        for robot in self.scenario.get("robots", []):
            if not robot.get("enabled", True):
                continue
            if str(robot.get("role", "")).strip().lower() in preferred_roles:
                return str(robot["id"])

        raise ValueError(
            "No primary robot could be resolved from evaluation.primary_robot "
            "or robot roles"
        )

    def resolve_goal_parameters(self) -> Tuple[int, int, int]:
        action_goal_config = self.scenario.get("action_goals", {})
        reconnaissance_config = self.scenario.get("attack_reconnaissance", {})

        count_parameter = int(self.get_parameter("action_goal_count").value)
        seed_parameter = int(self.get_parameter("action_goal_seed").value)
        recon_parameter = int(self.get_parameter("reconnaissance_seed").value)

        configured_cells = action_goal_config.get("cells", [])
        configured_count = (
            len(configured_cells)
            if configured_cells
            else int(action_goal_config.get("count", 0))
        )

        goal_count = (
            count_parameter if count_parameter >= 0 else configured_count
        )
        goal_seed = (
            seed_parameter
            if seed_parameter >= 0
            else int(action_goal_config.get("seed", 0))
        )
        reconnaissance_seed = (
            recon_parameter
            if recon_parameter >= 0
            else int(reconnaissance_config.get("seed", goal_seed))
        )
        return goal_count, goal_seed, reconnaissance_seed

    def resolve_heatmap_path(self) -> Path:
        explicit = str(self.get_parameter("heatmap_path").value).strip()
        if explicit:
            return Path(os.path.expandvars(os.path.expanduser(explicit)))

        goal_count, goal_seed, reconnaissance_seed = (
            self.resolve_goal_parameters()
        )
        directory = Path(
            os.path.expandvars(
                os.path.expanduser(
                    str(self.get_parameter("heatmap_directory").value)
                )
            )
        )
        stem = (
            f"{self.map_name}_goals-{goal_count}_goal-seed-{goal_seed}"
            f"_recon-seed-{reconnaissance_seed}"
        )
        return directory / f"{stem}.json"

    @staticmethod
    def load_heatmap(path: Path) -> Tuple[Dict, List[HeatmapCell]]:
        if not path.exists():
            raise FileNotFoundError(
                "Attack heatmap JSON was not found. Expected: "
                f"{path}"
            )

        payload = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            raise ValueError(f"Heatmap root must be a JSON object: {path}")
        raw_cells = payload.get("cells")
        if not isinstance(raw_cells, list):
            raise ValueError(f"Heatmap is missing a cells list: {path}")

        cells: List[HeatmapCell] = []
        seen: Set[Cell] = set()
        for index, raw in enumerate(raw_cells):
            if not isinstance(raw, dict):
                raise ValueError(f"Heatmap cell #{index} must be an object")
            item = HeatmapCell(
                row=int(raw["row"]),
                col=int(raw["col"]),
                score=float(raw.get("score", 0.0)),
                route_frequency=float(raw.get("route_frequency", 0.0)),
                detour_impact=float(raw.get("detour_impact", 0.0)),
                chokepoint=float(raw.get("chokepoint", 0.0)),
            )
            if item.cell in seen:
                raise ValueError(f"Duplicate heatmap cell: {item.cell}")
            seen.add(item.cell)
            cells.append(item)

        cells.sort(key=lambda item: (-item.score, item.row, item.col))
        return payload, cells

    def validate_heatmap_identity(self) -> None:
        payload_map = str(self.heatmap_payload.get("map_name", ""))
        if payload_map and payload_map != self.map_name:
            raise ValueError(
                f"Heatmap map_name is {payload_map!r}, but the node was "
                f"started with map_name={self.map_name!r}"
            )

        goal_count, goal_seed, reconnaissance_seed = (
            self.resolve_goal_parameters()
        )
        checks = {
            "action_goal_count": goal_count,
            "action_goal_seed": goal_seed,
            "reconnaissance_seed": reconnaissance_seed,
        }
        for field, expected in checks.items():
            if field not in self.heatmap_payload:
                continue
            actual = int(self.heatmap_payload[field])
            if actual != expected:
                raise ValueError(
                    f"Heatmap {field}={actual}, expected {expected}. "
                    "The attack node and experiment are not using the same "
                    "seeded setup."
                )

    # ------------------------------------------------------------------
    # ROS callbacks
    # ------------------------------------------------------------------

    def plan_status_callback(self, msg: String) -> None:
        try:
            payload = json.loads(msg.data)
            if isinstance(payload, dict):
                self.plan_status = payload
        except json.JSONDecodeError as exc:
            self.get_logger().warning(f"Ignored malformed /plan_status: {exc}")

    def primary_route_callback(self, msg: NavPath) -> None:
        self.primary_route = self.path_message_to_cells(msg)

    def attacker_route_callback(self, msg: NavPath) -> None:
        self.attacker_route = self.path_message_to_cells(msg)

    def path_message_to_cells(self, msg: NavPath) -> List[Cell]:
        cells: List[Cell] = []
        for pose in msg.poses:
            x = float(pose.pose.position.x)
            y = float(pose.pose.position.y)
            cell = self.world_to_cell(x, y)
            if not cells or cells[-1] != cell:
                cells.append(cell)
        return cells

    def attack_timer_callback(self) -> None:
        if not self.enabled:
            return

        now_sec = self.now_sec()
        if now_sec - self.start_time_sec < self.start_delay_sec:
            return

        if (
            self.max_attack_events > 0
            and self.attack_event_count >= self.max_attack_events
        ):
            return

        if self.placement_policy in {"route_informed", "route_only"}:
            if not self.primary_route:
                self.get_logger().debug(
                    "Waiting for the primary robot route before attacking."
                )
                return

        selected_centers = self.select_object_centers(now_sec)
        if not selected_centers:
            self.get_logger().warning(
                "No eligible malicious-object cell was available for this event."
            )
            return

        event_index = self.attack_event_count + 1
        published_cells: List[Cell] = []

        for center in selected_centers:
            object_cells = self.expand_fake_object(center)
            for cell in object_cells:
                self.publish_occupied_claim(
                    cell=cell,
                    center=center,
                    event_index=event_index,
                    now_sec=now_sec,
                )
                self.last_attack_time_by_cell[cell] = now_sec
                published_cells.append(cell)

            self.used_object_centers.add(center)
            self.last_attack_time_by_cell[center] = now_sec

        self.attack_event_count = event_index
        self.get_logger().info(
            f"Malicious attack event {event_index}: attacker={self.attacker_id}, "
            f"centers={selected_centers}, claims={published_cells}"
        )

    # ------------------------------------------------------------------
    # Placement
    # ------------------------------------------------------------------

    def select_object_centers(self, now_sec: float) -> List[Cell]:
        eligible: List[Tuple[float, HeatmapCell]] = []
        route_set = set(self.primary_route)
        ego_cell = self.primary_route[0] if self.primary_route else None
        goal_cell = self.primary_route[-1] if self.primary_route else None
        attacker_cell = self.attacker_route[0] if self.attacker_route else None

        for item in self.heatmap_cells:
            cell = item.cell
            if item.score < self.minimum_heatmap_score:
                continue
            if not self.allow_repeat_object_center and cell in self.used_object_centers:
                continue
            if self.is_on_cooldown(cell, now_sec):
                continue
            if (
                ego_cell is not None
                and self.cell_distance(cell, ego_cell)
                <= self.ego_exclusion_radius_cells
            ):
                continue
            if (
                goal_cell is not None
                and self.cell_distance(cell, goal_cell)
                <= self.endpoint_exclusion_radius_cells
            ):
                continue
            if (
                attacker_cell is not None
                and self.report_range_cells > 0.0
                and self.cell_distance(cell, attacker_cell)
                > self.report_range_cells
            ):
                continue

            if self.placement_policy == "route_only" and cell not in route_set:
                continue

            placement_score = self.compute_placement_score(item, route_set)
            eligible.append((placement_score, item))

        eligible.sort(
            key=lambda pair: (-pair[0], -pair[1].score, pair[1].row, pair[1].col)
        )

        selected: List[Cell] = []
        remaining = list(eligible)
        while remaining and len(selected) < self.max_claims_per_event:
            if self.selection_mode == "highest":
                _, chosen = remaining.pop(0)
            else:
                pool_size = min(self.random_top_k, len(remaining))
                chosen_index = self.rng.randrange(pool_size)
                _, chosen = remaining.pop(chosen_index)

            selected.append(chosen.cell)

            # Prevent multiple selected centers from producing the same object.
            minimum_spacing = max(1.0, float(self.fake_object_radius_cells * 2 + 1))
            remaining = [
                pair
                for pair in remaining
                if self.cell_distance(pair[1].cell, chosen.cell) >= minimum_spacing
            ]

        return selected

    def compute_placement_score(
        self,
        item: HeatmapCell,
        route_set: Set[Cell],
    ) -> float:
        if self.placement_policy == "topology_only" or not route_set:
            return item.score

        if item.cell in route_set:
            route_relevance = 1.0
        else:
            nearest_route_distance = min(
                self.cell_distance(item.cell, route_cell)
                for route_cell in route_set
            )
            route_relevance = math.exp(
                -nearest_route_distance / self.route_distance_scale_cells
            )

        return item.score * (
            1.0 + self.route_relevance_weight * route_relevance
        )

    def expand_fake_object(self, center: Cell) -> List[Cell]:
        if self.fake_object_radius_cells <= 0:
            return [center]

        center_row, center_col = center
        cells: List[Cell] = []
        for d_row in range(
            -self.fake_object_radius_cells,
            self.fake_object_radius_cells + 1,
        ):
            for d_col in range(
                -self.fake_object_radius_cells,
                self.fake_object_radius_cells + 1,
            ):
                candidate = (center_row + d_row, center_col + d_col)
                if math.hypot(d_row, d_col) > self.fake_object_radius_cells:
                    continue
                if candidate not in self.heatmap_by_cell:
                    continue
                cells.append(candidate)

        cells.sort(key=lambda cell: (self.cell_distance(cell, center), cell))
        return cells or [center]

    def is_on_cooldown(self, cell: Cell, now_sec: float) -> bool:
        previous = self.last_attack_time_by_cell.get(cell)
        if previous is None:
            return False
        return now_sec - previous < self.cell_cooldown_sec

    # ------------------------------------------------------------------
    # Claim publication
    # ------------------------------------------------------------------

    def publish_occupied_claim(
        self,
        *,
        cell: Cell,
        center: Cell,
        event_index: int,
        now_sec: float,
    ) -> None:
        heatmap_item = self.heatmap_by_cell.get(cell)
        center_item = self.heatmap_by_cell[center]

        payload = {
            "robot_id": self.attacker_id,
            "row": int(cell[0]),
            "col": int(cell[1]),
            "report_type": "occupied",
            "timestamp": float(now_sec),
            "confidence": float(self.confidence),
            "metadata": {
                "attack": True,
                "attack_type": "heatmap_fake_object",
                "attack_event": int(event_index),
                "placement_policy": self.placement_policy,
                "selection_mode": self.selection_mode,
                "object_center": [int(center[0]), int(center[1])],
                "object_radius_cells": int(self.fake_object_radius_cells),
                "heatmap_score": float(
                    heatmap_item.score if heatmap_item is not None else 0.0
                ),
                "center_heatmap_score": float(center_item.score),
                "route_frequency": float(
                    heatmap_item.route_frequency
                    if heatmap_item is not None
                    else 0.0
                ),
                "detour_impact": float(
                    heatmap_item.detour_impact
                    if heatmap_item is not None
                    else 0.0
                ),
                "chokepoint": float(
                    heatmap_item.chokepoint
                    if heatmap_item is not None
                    else 0.0
                ),
                "heatmap_file": self.heatmap_path.name,
                "primary_robot": self.primary_robot_id,
            },
        }

        if self.report_trust >= 0.0:
            payload["report_trust"] = self.clamp01(self.report_trust)

        message = String()
        message.data = json.dumps(payload, sort_keys=True)
        self.claim_pub.publish(message)

    # ------------------------------------------------------------------
    # Helpers and diagnostics
    # ------------------------------------------------------------------

    def world_to_cell(self, x: float, y: float) -> Cell:
        return (
            int(math.floor(y / self.cell_size_m)),
            int(math.floor(x / self.cell_size_m)),
        )

    @staticmethod
    def cell_distance(a: Cell, b: Cell) -> float:
        return math.hypot(a[0] - b[0], a[1] - b[1])

    @staticmethod
    def clamp01(value: float) -> float:
        return max(0.0, min(1.0, value))

    def now_sec(self) -> float:
        return self.get_clock().now().nanoseconds / 1_000_000_000.0

    def print_startup_summary(self) -> None:
        positive_cells = sum(1 for item in self.heatmap_cells if item.score > 0.0)
        self.get_logger().info("")
        self.get_logger().info("========== Malicious Object Node ==========")
        self.get_logger().info(f"Enabled: {self.enabled}")
        self.get_logger().info(f"Attacker: {self.attacker_id}")
        self.get_logger().info(f"Primary robot: {self.primary_robot_id}")
        self.get_logger().info(f"Placement policy: {self.placement_policy}")
        self.get_logger().info(f"Selection mode: {self.selection_mode}")
        self.get_logger().info(f"Heatmap: {self.heatmap_path}")
        self.get_logger().info(
            f"Heatmap cells: {len(self.heatmap_cells)} total, "
            f"{positive_cells} positive"
        )
        self.get_logger().info(
            f"Attack timing: delay={self.start_delay_sec:.3f}s, "
            f"period={self.report_period_sec:.3f}s, "
            f"max_events={self.max_attack_events or 'unlimited'}"
        )
        self.get_logger().info(
            f"Fake object: radius={self.fake_object_radius_cells} cells, "
            f"centers_per_event={self.max_claims_per_event}, "
            f"confidence={self.confidence:.3f}"
        )
        self.get_logger().info("===========================================")
        self.get_logger().info("")


def main(args: Optional[Sequence[str]] = None) -> None:
    rclpy.init(args=args)
    node: Optional[MaliciousObjectNode] = None
    try:
        node = MaliciousObjectNode()
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        if node is not None:
            node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
